### ISSUE TITLE
Standarize Logger

### ISSUE THREAD

**Issue by icemagno** [mpetazzoni/ttorrent#117]
I'm trying to use ttorrent embedded in a java web application, but I'm already using Log4J, 
When you use the interfaces 

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

You're causing conflicts on catalina logger (and mine).
Please change to

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

This way you avoid using slf4j libs and make your JAR Tomcat-ready.

**Comment by mpetazzoni** [comment]
I disagree. slf4j is the best choice for logging within a library, because it leaves the choice of the actual logging implementation to the developer embedding the library into her/his application via the use of slf4j bindings, which are available to all major logging implementations (log4j, java.util.logging, etc.). See http://slf4j.org for more info.

**Comment by icemagno** [comment]
Agree.. and thanks for leaving us to choice.
But doing this we cannot use it within a web container...

Magno.

2015-02-13 4:57 GMT-02:00 Maxime Petazzoni <notifications@github.com>:

**Comment by mpetazzoni** [comment]
You should still be able to. What's the conflict you're seeing exactly? Maybe you need to build a shaded JAR for `ttorrent` instead.

**Comment by icemagno** [comment]
Hi Mr. Maxime,
Thanks for reply.

Well, all is fine now.
I forked ttorrend and do the modifications.
Only removed slf4j package.
Your POM is somehow injecting log4j package anyway and its conflicting with
my container and applications.

By removing slf4j dependency entry and changing your logger to use
*org.apache.logging.log4j
interfaces,*
*I can use just the log4j package.*

Now I can merge your logger with mine, doing configurations inside my
log4j.xml file ( your appender creation was removed,
since my XML have two - file and console). Now I can enable and disabe
loggin by selecting just the class I need to see or
send one to console, others to file.

Example:

* <Logger name="com.turn.ttorrent.client.Client" level="debug"> *
* <appender-ref ref="File"/> *
* </Logger>*

will enable the Client class at debug level and send to file.

* <Logger name="com.turn.ttorrent.client.Client" level="error"> *
* <appender-ref ref="Console"/> *
* </Logger>*

will enable at error level and send to console.

All of this inside my already logging application.
It is very, very easy for me now.

Please understand: I am not criticizing your method. I know it's very good
and more flexible.
But I have a very specific situation, where I need to EMBED ttorrent inside
a web application and it is not very common.

And.... you are using log4j package anyway, so I just remove what is left.
One package less, web container embed ready, per class logging.

I just ask you to never merge my fork as I write a warning at my page.
You can see the warning here:

*https://github.com/icemagno/ttorrent
<https://github.com/icemagno/ttorrent>*

*I appreciate your attention and hope you are not angry I forked your
project and done this doubtful work.*

*Cheers.*

*Carlos Magno.*








2015-02-17 14:38 GMT-02:00 Maxime Petazzoni <notifications@github.com>:

**Comment by cjmalloy** [comment]
Is the issue just that sl4f is not being imported properly? Currently it is:


		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.6.4</version>
		</dependency>

But I think this is pulling in log4j for the CLI. I believe to just pull in the facad you use:

    <dependency>
    	<groupId>org.slf4j</groupId>
    	<artifactId>slf4j-api</artifactId>
    	<version>1.6.4</version>
    </dependency>

And maybe it would be a good idea to split off the CLI as a separate module so it can use log4j independently.

**Comment by mpetazzoni** [comment]
@cjmalloy Yes, that's the source of the problem. The main reason I import `slf4j-log4j12` is because one can run `ttorrent` as a standalone program and it needs a logging implementation. But that's just because of my laziness. I should have a Maven module for the library, which depends on `slf4j-api`, and a distinct module for the binaries, which depends on the library and on `slf4j-log4j12`. I'd happily welcome a pull request implementing this change!

**Comment by cjmalloy** [comment]
https://github.com/mpetazzoni/ttorrent/pull/119
