### ISSUE TITLE
About getting info on the torrent

### ISSUE THREAD

**Issue by dream-s** [mpetazzoni/ttorrent#126]
Hello, well its not exactly an issue, what I want to know is how to get torrent info (all kinds of info)
such as torrent progress in a String which can be used  for example in an progress bar or a table to display the info to the user.

Ty in advance.

**Comment by mpetazzoni** [comment]
If you look at the `info()` method in `Client`, it shows how to get all that information. This function only logs, but it shows the process for calculating the information that you want. You have access to the torrent via `client.getTorrent()`, and to the connected peers via the `getPeers()` method, which you need to filter the results by looking at each peer's `isConnected()`.

**Comment by GuacheSuede** [comment]
Hello @mpetazzoni , i tried using the `getPeers()` method, but could not find `isConnected()` method, am i doing anything wrong ? (Trying to find number of seeders and leechers number) Thank You

**Comment by mpetazzoni** [comment]
You won't directly get seeders/leechers info from ttorrent, as that information isn't really used by the BitTorrent protocol to figure out anything. You can derive it from the `SharingPeer`s objects returned by `getPeers()` though. A leecher is a connected peer that is not offering any piece for download (`getAvailablePieces()` returns an empty bitset), while a seeder is a peer that has all pieces available (`getAvailablePieces()` returns a full bitset).

HTH!
