### ISSUE TITLE
java.io.IOException: No available port for the BitTorrent client!

### ISSUE THREAD

**Issue by tchoulihan** [mpetazzoni/ttorrent#132]
I'm getting this error, and have a couple of questions:

Here's my code I run for each torrent file I'm sharing:
```java
	Client client = new Client(InetAddress.getLocalHost(),
				SharedTorrent.fromFile(torrentFile, outputParent));
		
		client.setMaxDownloadRate(50.0);
		client.setMaxUploadRate(50.0);
		client.share();
```

1) Do I have to instantiate client for every new torrent file? It seems to me that I should have a single client, that can add or remove torrent files. 

2) If this is the case, then the port ranges, should be similar to other clients, usually, 49152-65535

**Comment by mpetazzoni** [comment]
Yes, a `Client` in this case deals with a single torrent file.
