### ISSUE TITLE
ttorrent not working: connection timed out for all peers

### ISSUE THREAD

**Issue by tchoulihan** [mpetazzoni/ttorrent#136]
Does anyone have ttorrent working right now? I started to build a framework around it without testing it out, but now I'm trying to download a torrent with it, and it's stalled on every peer. Here's the type warning messages I'm getting:

```
18:45:20.514 [bt-announce(..376131)] WARN  c.t.t.client.announce.Announce - No response or unreachable tracker!

18:43:24.690 [bt-connect-12] WARN  com.turn.ttorrent.client.Client - Could not connect to peer://109.154.162.171:12370/? [Ci|Ci|0]: No route to host.

18:43:24.799 [bt-connect-8] WARN  com.turn.ttorrent.client.Client - Could not connect to peer://155.254.99.114:57351/? [Ci|Ci|0]: Handshake size read underrrun.

18:43:25.108 [bt-connect-8] WARN  com.turn.ttorrent.client.Client - Could not connect to peer://43.247.158.11:13881/? [Ci|Ci|0]: Connection refused.

18:45:31.778 [bt-connect-5] WARN  com.turn.ttorrent.client.Client - Could not connect to peer://107.214.91.59:51413/? [Ci|Ci|0]: Connection timed out.
```

I tried using deluge to download the same file, which uses libtorrent, and that's having no problems.

**Comment by tchoulihan** [comment]
I'm seeing people with similar issues in #43 and #85

**Comment by tchoulihan** [comment]
I just verified that the issue with the previous torrent was that for some reason ttorrent doesn't work with very large files, over 1GB. 

I'm also finding that download resuming doesn't appear to work. I'm going to split these into separate issues.

**Comment by mpetazzoni** [comment]
Thanks; closing this issue in favor of the other ones.
