### ISSUE TITLE
ttorrent won't resume downloading

### ISSUE THREAD

**Issue by tchoulihan** [mpetazzoni/ttorrent#138]
I started downloading a 300MB torrent, then killed my client, and restarted it hoping to see a resume after those pieces. But I get the following errors repeating:
```
12:40:40.706 [bt-connect-6] WARN  com.turn.ttorrent.client.Client - Could not connect to peer://197.221.81.162:6881/?  [Ci|Ci|0]: Connection timed out.

12:40:44.135 [bt-client(..623532)] DEBUG com.turn.ttorrent.client.Client - SHARING 16/1329 pieces (1.20%) [0/0] with 0/2 peers at 0.00/0.00 kB/s.
```

The speed always stays at 0kB/s, and has stopped looking for more peers.

**Comment by lalkmim** [comment]
I think it's the same problem I had on #91.

**Comment by tchoulihan** [comment]
Yep it does.

**Comment by mpetazzoni** [comment]
Thanks, marking duplicate.
