### ISSUE TITLE
multiple downloads

### ISSUE THREAD

**Issue by Rimander** [mpetazzoni/ttorrent#141]
Hi.
I cant download multiple torrents.
1 its possible, but 2 no.

WARNING [bt-connect-15] com.turn.ttorrent.client.Client.handleFailedConnection Could not connect to peer://108.93.184.23:55394/?
 WARNING [bt-connect-9] com.turn.ttorrent.client.Client.handleFailedConnection Could not connect to peer://141.135.98.104:28114/? [Ci|Ci|0]: Connection timed out: connect.
WARNING [bt-connect-19] com.turn.ttorrent.client.Client.handleFailedConnection Could not connect to peer://92.108.125.11:61848/? [Ci|Ci|0]: Connection timed out: connect.
WARNING [bt-connect-7] com.turn.ttorrent.client.Client.handleFailedConnection Could not connect to peer://50.163.241.234:43611/? [Ci|Ci|0]: Connection timed out: connect.

**Comment by mpetazzoni** [comment]
A `Client` instance only deals with a single torrent download. If you want to download multiple torrents at the same time, you need multiple clients.

That being said, I'm not sure how your log messages are related here. It looks like those peers simply aren't reachable.
