### ISSUE TITLE
Client is unable to reach Trackers!

### ISSUE THREAD

**Issue by talothman** [mpetazzoni/ttorrent#157]
I'm working on a GUI implementation for this library but can't get the simple ClientMain in the cli module to run properly. For some reason it is unable to connect to the assigned Tracker from a loaded metoinfo file. Code compiles fine and all but then when it runs the Announce loop, it is not able to contact the Tracker. The output message is: 

**[bt-announce(..376434)    ] WARN : No response or unreachable tracker!**

I have tried multiple metainfo files, large, small and have tested them on another bittorrent clients and they work fine there. I have also attempted to turn off my firewall and every other network security issue might be causing this but nothing has changed. A sample recurring output from the logger is the following:

> 2015-12-09 18:53:36,011 [main                     ] INFO : Multi-file torrent information:
> 2015-12-09 18:53:36,012 [main                     ] INFO :   Torrent name: testmp3testfile
> 2015-12-09 18:53:36,012 [main                     ] INFO :   Announced at:
> 2015-12-09 18:53:36,014 [main                     ] INFO :      1. http://bt1.archive.org:6969/announce
> 2015-12-09 18:53:36,015 [main                     ] INFO :      2. http://bt2.archive.org:6969/announce
> 2015-12-09 18:53:36,019 [main                     ] INFO :   Created on..: Wed Nov 05 14:56:24 EST 2014
> 2015-12-09 18:53:36,019 [main                     ] INFO :   Comment.....: This content hosted at the Internet Archive at http://archive.org/details/testmp3testfile
> Files may have changed, which prevents torrents from downloading correctly or completely; please check for an updated torrent at http://archive.org/download/testmp3testfile/testmp3testfile_archive.torrent
> Note: retrieval usually requires a client that supports webseeding (GetRight style).
> Note: many Internet Archive torrents contain a 'pad file' directory. This directory and the files within it may be erased once retrieval completes.
> Note: the file testmp3testfile_meta.xml contains metadata about this torrent's contents.
> 2015-12-09 18:53:36,019 [main                     ] INFO :   Created by..: ia_make_torrent
> 2015-12-09 18:53:36,019 [main                     ] INFO :   Found 5 file(s) in multi-file torrent structure.
> 2015-12-09 18:53:36,019 [main                     ] DEBUG:      1. testmp3testfile\mpthreetest.mp3 (198,658 byte(s))
> 2015-12-09 18:53:36,020 [main                     ] DEBUG:      2. testmp3testfile\mpthreetest.ogg (113,206 byte(s))
> 2015-12-09 18:53:36,020 [main                     ] DEBUG:      3. testmp3testfile\mpthreetest.png (9,748 byte(s))
> 2015-12-09 18:53:36,021 [main                     ] DEBUG:      4. testmp3testfile\testmp3testfile_64kb.m3u (64 byte(s))
> 2015-12-09 18:53:36,021 [main                     ] DEBUG:      5. testmp3testfile\testmp3testfile_meta.xml (1,038 byte(s))
> 2015-12-09 18:53:36,021 [main                     ] INFO :   Pieces......: 1 piece(s) (524288 byte(s)/piece)
> 2015-12-09 18:53:36,021 [main                     ] INFO :   Total size..: 322,714 byte(s)
> 2015-12-09 18:53:36,027 [main                     ] DEBUG: Partial download found at C:\Users\Talal\Desktop\tmp\testmp3testfile\mpthreetest.mp3.part. Continuing...
> 2015-12-09 18:53:36,031 [main                     ] INFO : Initialized byte storage file at C:\Users\Talal\Desktop\tmp\testmp3testfile\mpthreetest.mp3.part (0+198658 byte(s)).
> 2015-12-09 18:53:36,032 [main                     ] DEBUG: Partial download found at C:\Users\Talal\Desktop\tmp\testmp3testfile\mpthreetest.ogg.part. Continuing...
> 2015-12-09 18:53:36,034 [main                     ] INFO : Initialized byte storage file at C:\Users\Talal\Desktop\tmp\testmp3testfile\mpthreetest.ogg.part (198658+113206 byte(s)).
> 2015-12-09 18:53:36,034 [main                     ] DEBUG: Partial download found at C:\Users\Talal\Desktop\tmp\testmp3testfile\mpthreetest.png.part. Continuing...
> 2015-12-09 18:53:36,036 [main                     ] INFO : Initialized byte storage file at C:\Users\Talal\Desktop\tmp\testmp3testfile\mpthreetest.png.part (311864+9748 byte(s)).
> 2015-12-09 18:53:36,037 [main                     ] DEBUG: Partial download found at C:\Users\Talal\Desktop\tmp\testmp3testfile\testmp3testfile_64kb.m3u.part. Continuing...
> 2015-12-09 18:53:36,037 [main                     ] INFO : Initialized byte storage file at C:\Users\Talal\Desktop\tmp\testmp3testfile\testmp3testfile_64kb.m3u.part (321612+64 byte(s)).
> 2015-12-09 18:53:36,038 [main                     ] DEBUG: Partial download found at C:\Users\Talal\Desktop\tmp\testmp3testfile\testmp3testfile_meta.xml.part. Continuing...
> 2015-12-09 18:53:36,038 [main                     ] INFO : Initialized byte storage file at C:\Users\Talal\Desktop\tmp\testmp3testfile\testmp3testfile_meta.xml.part (321676+1038 byte(s)).
> 2015-12-09 18:53:36,042 [main                     ] INFO : Initialized torrent byte storage on 5 file(s) (322714 total byte(s)).
> 2015-12-09 18:53:36,126 [main                     ] WARN : Could not bind to Home/172.20.165.252:49152, trying next port...
> 2015-12-09 18:53:36,126 [main                     ] WARN : Could not bind to Home/172.20.165.252:49153, trying next port...
> 2015-12-09 18:53:36,126 [main                     ] WARN : Could not bind to Home/172.20.165.252:49154, trying next port...
> 2015-12-09 18:53:36,126 [main                     ] WARN : Could not bind to Home/172.20.165.252:49155, trying next port...
> 2015-12-09 18:53:36,126 [main                     ] WARN : Could not bind to Home/172.20.165.252:49156, trying next port...
> 2015-12-09 18:53:36,126 [main                     ] WARN : Could not bind to Home/172.20.165.252:49157, trying next port...
> 2015-12-09 18:53:36,127 [main                     ] WARN : Could not bind to Home/172.20.165.252:49158, trying next port...
> 2015-12-09 18:53:36,127 [main                     ] WARN : Could not bind to Home/172.20.165.252:49159, trying next port...
> 2015-12-09 18:53:36,127 [main                     ] WARN : Could not bind to Home/172.20.165.252:49160, trying next port...
> 2015-12-09 18:53:36,127 [main                     ] WARN : Could not bind to Home/172.20.165.252:49161, trying next port...
> 2015-12-09 18:53:36,127 [main                     ] WARN : Could not bind to Home/172.20.165.252:49162, trying next port...
> 2015-12-09 18:53:36,127 [main                     ] WARN : Could not bind to Home/172.20.165.252:49163, trying next port...
> 2015-12-09 18:53:36,127 [main                     ] WARN : Could not bind to Home/172.20.165.252:49164, trying next port...
> 2015-12-09 18:53:36,128 [main                     ] INFO : Listening for incoming connections on Home/172.20.165.252:49165.
> 2015-12-09 18:53:36,169 [main                     ] INFO : Initialized announce sub-system with 2 trackers on testmp3testfile.
> 2015-12-09 18:53:36,170 [main                     ] INFO : BitTorrent client [..376434] for testmp3testfile started and listening at 172.20.165.252:49165...
> 2015-12-09 18:53:36,177 [bt-client(..376434)      ] INFO : Analyzing local data for testmp3testfile with 8 threads (1 pieces)...
> 2015-12-09 18:53:36,206 [bt-client(..376434)      ] DEBUG: testmp3testfile: we have 0/322714 bytes (0.0%) [0/1 pieces].
> 2015-12-09 18:53:36,206 [bt-announce(..376434)    ] INFO : Starting announce loop...
> 2015-12-09 18:53:36,210 [bt-announce(..376434)    ] INFO : Announcing STARTED to tracker with 0U/0D/322714L bytes...
> 2015-12-09 18:53:36,217 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> 2015-12-09 18:53:39,217 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> 2015-12-09 18:53:42,218 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> 2015-12-09 18:53:45,219 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> 2015-12-09 18:53:48,219 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> 2015-12-09 18:53:51,220 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> 2015-12-09 18:53:54,220 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> 2015-12-09 18:53:57,221 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> **2015-12-09 18:53:57,766 [bt-announce(..376434)    ] WARN : No response or unreachable tracker!**
> 2015-12-09 18:53:57,766 [bt-announce(..376434)    ] DEBUG: Switched to tracker client for http://bt2.archive.org:6969/announce (tier 1, position 0).
> 2015-12-09 18:54:00,222 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> 2015-12-09 18:54:02,766 [bt-announce(..376434)    ] INFO : Announcing STARTED to tracker with 0U/0D/322714L bytes...
> 2015-12-09 18:54:03,222 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> 2015-12-09 18:54:06,222 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> 2015-12-09 18:54:09,225 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> 2015-12-09 18:54:12,227 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> 2015-12-09 18:54:15,227 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> 2015-12-09 18:54:18,228 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> 2015-12-09 18:54:21,229 [bt-client(..376434)      ] INFO : SHARING 0/1 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
> **2015-12-09 18:54:24,210 [bt-announce(..376434)    ] WARN : No response or unreachable tracker!**
> 2015-12-09 18:54:24,210 [bt-announce(..376434)    ] DEBUG: Switched to tracker client for http://bt1.archive.org:6969/announce (tier 0, position 0).

Any idea why this might be happening. I have not changed anything to the cli module code and it still isn't working. Could this be an issue with my network, specifically the LAN I'm on (University provided; possible issues with NAT)?

**Comment by mpetazzoni** [comment]
Can you reach `bt1.archive.org:6969` (using telnet for example)?
