### ISSUE TITLE
How automatically update JProgressBar?

### ISSUE THREAD

**Issue by MaximDzhezhelo** [mpetazzoni/ttorrent#158]
I want to implement a download progress bar torrent file on the panel. to display the boot process using JProgressBar.
The question is how to take data from the Client that would automatically update JProgressBar.

**Comment by mpetazzoni** [comment]
Look at `Client.java`'s `info()` method: https://github.com/mpetazzoni/ttorrent/blob/master/core/src/main/java/com/turn/ttorrent/client/Client.java#L443

It shows how to get the most up-to-date information about the progress of the download. You can use that to update your progress bar as often as you need to, but `ttorrent` isn't going to do that automatically for you (you can use a thread on the side to do that for example).

HTH

**Comment by MaximDzhezhelo** [comment]
Thank you very much for taking the time to answer my question.
Please tell me the answer to another question.
how to increase the download speed of the file? I get that a torrent file
is the average size of up to 1 GB shakes on average 3 - 4 hours, but if you
use the conventional Torenth downloads 5 minutes. tell me how to increase
the speed?

2015-12-21 2:53 GMT+02:00 Maxime Petazzoni <notifications@github.com>:

> Look at Client.java's info() method:
> https://github.com/mpetazzoni/ttorrent/blob/master/core/src/main/java/com/turn/ttorrent/client/Client.java#L443
>
> It shows how to get the most up-to-date information about the progress of
> the download. You can use that to update your progress bar as often as you
> need to, but ttorrent isn't going to do that automatically for you (you
> can use a thread on the side to do that for example).
>
> HTH
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mpetazzoni/ttorrent/issues/158#issuecomment-166169093>
> .
>



-- 
С уважением, Максим Джежело.
+38(095)-337-35-38
