### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by t-pankajkumar** [mpetazzoni/ttorrent#159]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/PankajKumar/.m2/repository/org/slf4j/slf4j-simple/1.6.4/slf4j-simple-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/PankajKumar/.m2/repository/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
172 [main] INFO com.turn.ttorrent.common.Torrent - Multi-file torrent information:
172 [main] INFO com.turn.ttorrent.common.Torrent -   Torrent name: Lynda - JavaScript Essential Training
175 [main] INFO com.turn.ttorrent.common.Torrent -   Announced at:
207 [main] INFO com.turn.ttorrent.common.Torrent -      1. udp://tracker.coppersurfer.tk:6969/announce
207 [main] INFO com.turn.ttorrent.common.Torrent -      2. udp://tracker.openbittorrent.com:80/announce
207 [main] INFO com.turn.ttorrent.common.Torrent -      3. udp://glotorrents.pw:6969/announce
207 [main] INFO com.turn.ttorrent.common.Torrent -      4. udp://tracker.publicbt.com:80/announce
207 [main] INFO com.turn.ttorrent.common.Torrent -      5. udp://tracker.istole.it:80/announce
207 [main] INFO com.turn.ttorrent.common.Torrent -      6. udp://glotorrents.com:6969/announce
207 [main] INFO com.turn.ttorrent.common.Torrent -      7. udp://t1.pow7.com:80/announce
223 [main] INFO com.turn.ttorrent.common.Torrent -      8. udp://tracker.1337x.org:80/announce
223 [main] INFO com.turn.ttorrent.common.Torrent -      9. udp://tracker.glotorrents.com:6969/announce
223 [main] INFO com.turn.ttorrent.common.Torrent -     10. udp://tracker.pow7.com:80/announce
223 [main] INFO com.turn.ttorrent.common.Torrent -   Created on..: Mon Feb 17 18:09:14 IST 2014
223 [main] INFO com.turn.ttorrent.common.Torrent -   Comment.....: Torrent downloaded from torrent cache at http://torcache.net/
223 [main] INFO com.turn.ttorrent.common.Torrent -   Created by..: ruTorrent (PHP Class - Adrien Gibrat)
223 [main] INFO com.turn.ttorrent.common.Torrent -   Found 4 file(s) in multi-file torrent structure.
239 [main] INFO com.turn.ttorrent.common.Torrent -   Pieces......: 1974 piece(s) (262144 byte(s)/piece)
239 [main] INFO com.turn.ttorrent.common.Torrent -   Total size..: 517,287,207 byte(s)
239 [main] INFO com.turn.ttorrent.client.storage.FileStorage - Initialized byte storage file at H:\Lynda - JavaScript Essential Training\tracked_by_h33t_com.txt.part (0+185 byte(s)).
239 [main] INFO com.turn.ttorrent.client.storage.FileStorage - Initialized byte storage file at H:\Lynda - JavaScript Essential Training\Torrent downloaded from AhaShare.com.txt.part (185+58 byte(s)).
254 [main] INFO com.turn.ttorrent.client.storage.FileStorage - Initialized byte storage file at H:\Lynda - JavaScript Essential Training\Torrent Downloaded From ExtraTorrent.cc.txt.part (243+352 byte(s)).
254 [main] INFO com.turn.ttorrent.client.storage.FileStorage - Initialized byte storage file at H:\Lynda - JavaScript Essential Training\JavaScript Essential Training.tgz.part (595+517286612 byte(s)).
254 [main] INFO com.turn.ttorrent.client.storage.FileCollectionStorage - Initialized torrent byte storage on 4 file(s) (517287207 total byte(s)).
989 [main] INFO com.turn.ttorrent.client.ConnectionHandler - Listening for incoming connections on Pankaj/192.168.155.1:6881.
1473 [main] INFO com.turn.ttorrent.client.announce.Announce - Initialized announce sub-system with 10 trackers on Lynda - JavaScript Essential Training.
1486 [main] INFO com.turn.ttorrent.client.Client - BitTorrent client [..643035] for Lynda - JavaScript Essential Training started and listening at 192.168.155.1:6881...
1487 [bt-client(..643035)] INFO com.turn.ttorrent.client.SharedTorrent - Analyzing local data for Lynda - JavaScript Essential Training with 4 threads (1974 pieces)...
2081 [bt-client(..643035)] INFO com.turn.ttorrent.client.SharedTorrent -   ... 10% complete
2487 [bt-client(..643035)] INFO com.turn.ttorrent.client.SharedTorrent -   ... 20% complete
2862 [bt-client(..643035)] INFO com.turn.ttorrent.client.SharedTorrent -   ... 30% complete
3206 [bt-client(..643035)] INFO com.turn.ttorrent.client.SharedTorrent -   ... 40% complete
3550 [bt-client(..643035)] INFO com.turn.ttorrent.client.SharedTorrent -   ... 50% complete
3876 [bt-client(..643035)] INFO com.turn.ttorrent.client.SharedTorrent -   ... 60% complete
4235 [bt-client(..643035)] INFO com.turn.ttorrent.client.SharedTorrent -   ... 70% complete
4579 [bt-client(..643035)] INFO com.turn.ttorrent.client.SharedTorrent -   ... 80% complete
4922 [bt-client(..643035)] INFO com.turn.ttorrent.client.SharedTorrent -   ... 90% complete
5329 [bt-announce(..643035)] INFO com.turn.ttorrent.client.announce.Announce - Starting announce loop...
5329 [bt-announce(..643035)] INFO com.turn.ttorrent.client.announce.UDPTrackerClient - Announcing STARTED to tracker with 0U/0D/342175015L bytes...
5329 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
8329 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
11332 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
14337 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
17340 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
20344 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
23350 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
26358 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
29361 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
32365 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
35370 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
38372 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
41376 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
44379 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
47387 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
50390 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
53454 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
56457 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
59464 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
62473 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
65489 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
68498 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
71501 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
74507 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
77512 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
80513 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
83527 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
86529 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
89532 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
92536 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
95553 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
98568 [bt-client(..643035)] INFO com.turn.ttorrent.client.Client - SHARING 668/1974 pieces (33.84%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.

**Comment by mpetazzoni** [comment]
A patch was just merged that should fix most download issues.
