### ISSUE TITLE
View download progress

### ISSUE THREAD

**Issue by sockmonkeyws** [mpetazzoni/ttorrent#165]
Is there a way to query percentage of file downloaded?

**Comment by icemagno** [comment]
You can find some useful examples here:
https://github.com/icemagno/torfolder-server

**Comment by TanJay** [comment]
Yah there is a way. As #icemagno showed There is away. 
If you wanna update in gui just create a new thread.
```
public void run(){
                **float completion = client.getTorrent().getCompletion();**
                double timeEarly = System.currentTimeMillis();
                **while(!(completion==100)){**
                    float pastCompletion = completion;
                   ** completion=client.getTorrent().getCompletion();**
                    long speed = 0;
                    if(pastCompletion != completion){
                        speed =(long) ((completion-pastCompletion)/1024)/(TimeUnit.MILLISECONDS.toSeconds((long) (System.currentTimeMillis()-timeEarly)));
                        timeEarly = System.currentTimeMillis();
                    }
                    
                    
                    System.out.println(**completion **+ " "+ client.getState()+ " " + " Downloaded " + ((client.getTorrent().getSize()/100)*client.getTorrent().getCompletion())/(1024*1024) +"/" + (client.getTorrent().getSize()/(1024*1024))+"mb" + "speed: " + speed +"kbps");
                    **int val = (int)completion;**
                    downloadProgress.setValue(val);
                    downloadProgress.setString(val + "%");
                    
                }    
            }       
        };   
        progressDisplay.start();
```

**Comment by henkel** [comment]
Instead of polling for the status you can also register an observer in your Client instance. There is an update for every completed piece.

        client.addObserver(new Observer() {
            @Override
            public void update(Observable observable, Object data) {
                Client client = (Client) observable;
                float completion = client.getTorrent().getCompletion();
                /* do something useful with the completion rate */
            }
        });

**Comment by mpetazzoni** [comment]
Thanks @henkel. I actually forgot I implemented that observer mechanism :) That would indeed be the best way of doing so. I'll add information in the README.
