### ISSUE TITLE
Is there anyway to know the DownloadSpeed accurately?

### ISSUE THREAD

**Issue by TanJay** [mpetazzoni/ttorrent#166]
I used something like this now
but still doesn't update frequently 

```
                float completion = client.getTorrent().getCompletion();
                double timeEarly = System.currentTimeMillis();
                long speed = 0;
                while(!(completion==100)){
                    float pastCompletion = completion;
                    completion=client.getTorrent().getCompletion();
                    if(pastCompletion != completion){
                        
                        speed =(int) ((completion-pastCompletion)/1024)/(TimeUnit.MILLISECONDS.toSeconds((long) (System.currentTimeMillis()-timeEarly)));
                        timeEarly = System.currentTimeMillis();
                    }
```

**Comment by lukyanets** [comment]
You can use example in README
`c.addObserver(new Observer() {
                @Override
                public void update(Observable observable, Object data) {
                    Client client = (Client) observable;
                    float dl = 0;
                    for (SharingPeer peer : client.getPeers()) {
                        if (peer.isConnected()) {
                            dl += peer.getDLRate().get();
                        }
                    }
                    // Update UI or something else
                    // dl speed in B/s
                    System.out.println(dl);

                }
            });
            c.waitForCompletion();`
