### ISSUE TITLE
How to know if some peer still downloading my file?

### ISSUE THREAD

**Issue by icemagno** [mpetazzoni/ttorrent#168]
I need to clean some Clients to open room to new ones.
But I need to know if my Client is serving active connection.
How to do this?

I've tried isConnected, isDownloading, but it is always false ...

**Comment by TanJay** [comment]
Yah in order to do that you can have different method! 
Not reliable bt still u can have.
**First one: **
(You can check the status of the torrent if status returned as SHARING it is still downloading, If it returned seeding it means the download has been completed)
`client.getState().toString()`
It is better to run a timer on a different thread to check the downloaded file size after few minutes if the file size doesnt change you can interrupt the client.

**Comment by icemagno** [comment]
Well, my question was how can I know when someone is downloading my file when I'm seeding, not if I've finished the download.
I have look into `client.getPeers()` and I can't conclude anything because I can't understand the all `peer.isXXX()` values ...

**Comment by icemagno** [comment]
No one?

	public void show() {
		for ( Client client : clients ) {
			ClientState state = client.getState();
			float completion = client.getTorrent().getCompletion();
			logger.debug(" > " + client.getTorrent().getCreatedBy() + " " + state + " " + completion + "%");
			for ( SharingPeer sp : client.getPeers() ) {
				logger.debug("    > " + sp.getIp() );
			}
		}
	}


I need to close a client only if no peers is downloading ....

How do the share( seconds ) method works? 

		SharedTorrent st = SharedTorrent.fromFile( tf, targetContentFolder );
		Client seeder = new Client( bindAddress, st);
	    seeder.share(1800); 


Will share for 1800 seconds and close or change status to ClientState.DONE ?

**Comment by mpetazzoni** [comment]
From the BitTorrent spec:

> A block is uploaded by a client when the client is not choking a peer, and that peer is interested in the client.

So if none of the connected peers are "interested" in us and we're not choking any of them on purpose, then none of them is downloading from us.

```java
boolean clientsDownloading = client.getPeers().filter(peer -> peer.isInterested() && !peer.isChoked()).count() == 0;
```
(Note that I haven't verified this in practice, so you should try).

For your second question, `share(seconds)` simply shares the torrent for the given amount of time and then shuts down ("seeding time").
