### ISSUE TITLE
byteArrayToHexString return wong result

### ISSUE THREAD

**Issue by XenonRaite** [mpetazzoni/ttorrent#173]
Leading 0 is missing in the output.

http://stackoverflow.com/questions/10275769/biginteger-tostring-method-is-deleting-leading-0

**Comment by henkel** [comment]
Submitted a fix, see #174

**Comment by XenonRaite** [comment]
thx!

**Comment by henkel** [comment]
@mpetazzoni I'm looking forward to release 1.5.1 with this bug fix :smile:
