### ISSUE TITLE
v1.5 - can't seem to download from maven repos

### ISSUE THREAD

**Issue by anirudha** [mpetazzoni/ttorrent#176]
can we deploy this?

**Comment by henkel** [comment]
Version 1.5 is available here: http://search.maven.org/#search%7Cga%7C1%7Cttorrent

**Comment by mpetazzoni** [comment]
Did I do something wrong with the release? @henkel and @anirudha, can you both confirm that the artifacts are deployed correctly? Thanks in advance!

**Comment by henkel** [comment]
It works for me. I'm consuming version 1.5 in [ttorrent-android-service](https://github.com/henkel/ttorrent-android-service/blob/master/library/build.gradle)
