### ISSUE TITLE
How to choose specific pieces to download? 

### ISSUE THREAD

**Issue by Mohamed-Mosaad** [mpetazzoni/ttorrent#179]

**Comment by mpetazzoni** [comment]
If you're using ttorrent as a library (and not just as a command-line tool), you can simply pass in the appropriate `RequestStrategy` to the `SharedTorrent` constructor:

https://github.com/mpetazzoni/ttorrent/blob/7acb2d0af3d007f8e64a35172b69713212177004/core/src/main/java/com/turn/ttorrent/client/SharedTorrent.java#L161
