### ISSUE TITLE
How to get name and size of the file to be downloaded

### ISSUE THREAD

**Issue by saibbyweb** [mpetazzoni/ttorrent#185]
I am using this library with Android Studio and I am successful in initiating the download. How can I fetch the name(s) and size(s) of the files which are being downloaded?

**Comment by saibbyweb** [comment]
I am using this library with Android Studio and I am successful in initiating the download. How can I fetch the name(s) and size(s) of the files which are being downloaded?

**Comment by mpetazzoni** [comment]
`client.getTorrent().getName()` and `client.getTorrent().getSize()`
