### ISSUE TITLE
Question about pushing to thousands of machines

### ISSUE THREAD

**Issue by paulvi** [mpetazzoni/ttorrent#214]
It is fascinated to see use of this library for distribution to many machines

>Although the write performance of the BitTorrent client is currently quite poor (~10MB/sec/connected peer), it has been measured that the distribution of a 150MB file to thousands of machines across several datacenters took no more than 30 seconds, with very little network overhead for the initial seeder (only 125% of the original file size uploaded by the initial seeder).

We need to do similar (having many our nodes).
However torrent protocol does not have push concept, and to make a file appear on a node, every node should be waiting for a seed to specific torrent file.

Does this library provide any special things? How could the push within datacenter work?

**Comment by mpetazzoni** [comment]
This library does not do that. `ttorrent` was developed as the distribution piece of a broader, agent-based orchestration system. The agents would receive a command from a controller that included a torrent file. The agents could then download the file locally using `ttorrent` and deploy it.

**Comment by paulvi** [comment]
Thanks, that makes sense.
