### ISSUE TITLE
Cannot add DownloadProgressListener in v2.0

### ISSUE THREAD

**Issue by AntonAleksandrov13** [mpetazzoni/ttorrent#220]
Seems like method 
`  public void addDownloadProgressListener(DownloadProgressListener listener)` in `SharedTorrent`
is already implemented, but I cannot find the way to use it. In my case, I am working with `SimpleClient` object.

Thanks for help in advance!

**Comment by Dead-off** [comment]
btw thank you for feedback!:)

**Comment by AntonAleksandrov13** [comment]
Thank you for the quick response and help!
