### ISSUE TITLE
TTORRENT_HASHING_THREADS configuration read incorrectly

### ISSUE THREAD

**Issue by vswamy** [mpetazzoni/ttorrent#221]
The static variables and blocks are executed in order they are specified in the java file. The [hashing executor](https://github.com/mpetazzoni/ttorrent/blob/master/common/src/main/java/com/turn/ttorrent/common/TorrentCreator.java#L29) is created before the configuration is read from the system environment and therefore this configuration is never reflected in the code. 

https://github.com/mpetazzoni/ttorrent/blob/db52f13ba709b26d9605d7ef18739cdaa7c5fc6d/common/src/main/java/com/turn/ttorrent/common/TorrentCreator.java#L364

**Comment by mpetazzoni** [comment]
@vswamy thanks for reporting! Do you think you'd be able to provide a PR with a fix? I'd be happy to review it and merge it!

**Comment by Dead-off** [comment]
@vswamy 
Thanks you, i moved this code before creating executor. So i think now it works correctly

**Comment by vswamy** [comment]
So fast. Thanks @Dead-off 

I have another concern related to how the number of threads are created. The Executor is created when the class get's loaded by jvm and usually happens when the application is booting up that is, when most of the processors (cpu) is free. 

Looking at the documentation of availableProcessors:
`    /**
     * Returns the number of processors available to the Java virtual machine.
     *
     * <p> This value may change during a particular invocation of the virtual
     * machine.  Applications that are sensitive to the number of available
     * processors should therefore occasionally poll this property and adjust
     * their resource usage appropriately. </p>
     *
     * @return  the maximum number of processors available to the virtual
     *          machine; never smaller than one
     * @since 1.4
     */
`

Should we be resetting the executor as the time goes by to reflect the CPU capacity available?

**Comment by mpetazzoni** [comment]
Thanks @Dead-off; closing this issue now then.
