### ISSUE TITLE
Maven packages is not up to date.

### ISSUE THREAD

**Issue by Kuinox** [mpetazzoni/ttorrent#225]
Hi,
The availabe maven package of ttorrent is the version 1.5 and is not up to date.  
Can you update the maven package ? Thanks.

**Comment by Dead-off** [comment]
i never loaded libraries into maven repo. How i understand for loading library private keys are requiring and only @mpetazzoni has they.

**Comment by asadsm** [comment]
So the following will import old code I'm assuming?

`compile 'com.turn:ttorrent-core:1.5'`

**Comment by Dead-off** [comment]
right

**Comment by asadsm** [comment]
Are you able to tag the new release though? That will enable importing it using tools like JitPack.

**Comment by Dead-off** [comment]
good idea:)
i will do it after fixing some problems

**Comment by Dead-off** [comment]
i tagged new release by ```ttorrent-2.0``` tag.
Without access to sonatype i cannot upload new version to maven central repo or jcenter but you can add jitpack repository and add dependency (see https://jitpack.io/)
```compile 'com.github.mpetazzoni:ttorrent:ttorrent-2.0'```
but it's unsecure way. Do it only if you trust to jitpack:)

**Comment by lanedas** [comment]
Hi,
tried your workaround of using jitpack. Unfortunately net.sf:jargs:1.0 is missing but I barely find a official repo which contains this lib. Do you have an idea?

Thanks!

**Comment by Dead-off** [comment]
try to add `maven { url 'https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/' }` in your build.gradle or similar line if you use maven. It's something like:
```
<repository>
    <id>jboss-thirdparty-releases</id>
    <name>JBoss Thirdparty Releases</name>
    <url>https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/</url>
</repository>
```

**Comment by lanedas** [comment]
thank you for your fast reply. will test it!

**Comment by mpetazzoni** [comment]
@Dead-off Do you know how I could transfer that ownership to you so you can publish new releases to Maven Central? I can't find any instructions about this is Sonatype's repository. You may have to contact them directly.

**Comment by EArminjon** [comment]
#251
