### ISSUE TITLE
support for webseeds in torrent creation

### ISSUE THREAD

**Issue by fireduck64** [mpetazzoni/ttorrent#239]
It would be helpful to be able to specify a web seed when creating a new torrent file with MetadataBuilder.

It would also be nice if I could hand in file info in the form of path, length and a list of sha1 hashes but that is kinda special to my needs.  I never actually have all the files on disk or in memory at once and reading from the streams is kinda expensive, so I like to do that only once.  Gathering the sha1 hashes every x bytes is easy though.  But anyways, not a big deal, I can work around that one.

**Comment by Dead-off** [comment]
can you link please specification about "web seed in torrent file"? I don't know what is it

**Comment by fireduck64** [comment]
Sorry, I should have included it.

http://bittorrent.org/beps/bep_0019.html

**Comment by Dead-off** [comment]
i added `setFilesInfo` method for creating metadata from hashes
https://github.com/mpetazzoni/ttorrent/commit/35b2303d038228c8cbb23336e0da608125ebaa62
try to use it
