### ISSUE TITLE
How to get download and upload speed in version 2.0?

### ISSUE THREAD

**Issue by Gonakt** [mpetazzoni/ttorrent#241]
The question is in the header of the issue. I tried to get a solution from another issues and source code, but didn't find anything helpful.

**Comment by Dead-off** [comment]
currently, you can't get speed via some API method but you can calculate it manually. Just add a listener and override `pieceDownloaded` method where you can piece size from an argument

**Comment by yoles** [comment]
Can u show a quick exemple please ? 
It's a little bit hard for me to understand how it works

**Comment by Dead-off** [comment]
something like this should work. This example will print each second average download speed until download will not be finished. Also, you can calculate the speed for the last N seconds using some queues
```
SimpleClient client = new SimpleClient();
    TorrentManager torrentManager = client.downloadTorrentAsync("torrent.file", "download/dir", InetAddress.getLocalHost());
    long start = System.currentTimeMillis();
    final AtomicLong downloadedBytes = new AtomicLong();
    final Semaphore semaphore = new Semaphore(0);
    torrentManager.addListener(new TorrentListenerWrapper() {
      @Override
      public void pieceDownloaded(PieceInformation pieceInformation, PeerInformation peerInformation) {
        downloadedBytes.addAndGet(pieceInformation.getSize());
      }

      @Override
      public void downloadComplete() {
        semaphore.release();
      }
    });

    while (!semaphore.tryAcquire(1, TimeUnit.SECONDS)) {
      System.out.println("average download speed " + (downloadedBytes.get() / (System.currentTimeMillis() - start)) + " bytes/ms");
    }
```

**Comment by yoles** [comment]
Thank you so much !
