### ISSUE TITLE
How to create a torrent?

### ISSUE THREAD

**Issue by Peterppan** [mpetazzoni/ttorrent#244]
how to cteate a .torrent file from the client？

**Comment by Dead-off** [comment]
use `MetadataBuilder` class
simple example:
```
byte[] torrentMetadataBytes = new MetadataBuilder()
            .addDataSource(new ByteArrayInputStream(new byte[]{1,2,3}), "singleFile.txt", true)
            .setTracker("http://localhost:12346")
            .buildBinary();
```
For adding local files you can use `addFile` method instead of `addDataSource`

**Comment by Peterppan** [comment]
Thank you very much for your answer，but i have confused about the other client how to download the shared files. When i create the .torrent file with the MetadataBuilder class, and which client be the seeder frist?

**Comment by Peterppan** [comment]
I create a .torrent file and use client download it,but the tracker allways get the request event NONE.
how can i fix it?

2019-07-22 14:18:18,026 [Dispatcher-4             ] WARN : RequestEvent event: NONE
2019-07-22 14:18:18,026 [Dispatcher-4             ] WARN : peer!!

**Comment by Dead-off** [comment]
Looks like you created a separate issue for this question. Ask me there
