### ISSUE TITLE
feature: Allow to check statistics of a given torrent

### ISSUE THREAD

**Issue by maarkeez** [mpetazzoni/ttorrent#247]
This is a feature request.
*  Allow to check statistics of a given torrent

I've created this pull request: 
* https://github.com/mpetazzoni/ttorrent/pull/246

Which content is: 
* Added to TorrentStatistic: percentage downladed, total bytes
* Added to SimpleClient: get statistics of a given torrent
* Added to SimpleClient, CommunicationManager: has stop

Please @mpetazzoni  let me know if you could review and if I have to change anything.
Thanks!

**Comment by Dead-off** [comment]
Thank you! I've commented on the pull request. Do there a little fix please and I'll merge it

**Comment by maarkeez** [comment]
@Dead-off please could you submit your review comments again?
 I do not see them in the pull request. Thanks!

**Comment by Dead-off** [comment]
done

**Comment by DavidMarquez-Copado** [comment]
Thanks! you can solve this feature request :)
