### ISSUE TITLE
Where can I find a documentation for this library

### ISSUE THREAD

**Issue by yassineakermi** [mpetazzoni/ttorrent#254]
Hello
I want to use this library but I couldn't find any documentation for it.
How do you guys know how to use this library? I'm quite a noob and I want to implement my own torrent client.
Thank you very much.

**Comment by Dead-off** [comment]
This library doesn't have good documentation. There is only an example in the readme file

**Comment by mpetazzoni** [comment]
The best examples are the implementations of the client, torrent generator and tracker themselves, available at https://github.com/mpetazzoni/ttorrent/tree/master/cli/src/main/java/com/turn/ttorrent/cli/
