### ISSUE TITLE
Not downloading - Help find problem

### ISSUE THREAD

**Issue by Nosfert** [mpetazzoni/ttorrent#43]
Hi
I have created a own torrent file with Utorrent. 
I have added some public trackers and i can download the file while using utorrent (im seeding from one computer).

But when trying to connect and download it with the TTorrent lib i get nowhere, i have tried other torrent files that i have not created and i can download those. 

I dont get any error message what i can see and i have even compared the logg info between the torrent files that i have created with the ones i have not created. 

I have even added loads of both udp and http trackers to my torrent and also added their trackers to my torrent. 

Is there any thoughts how to search on whats causing this error??

**Comment by vauvenal5** [comment]
Hi!

I seem to have the same issue.
The log says that it is downloading from 1/2 peers but nothing happens. I have gone as far as to set up a tracker per file I am trying to share but when I try to share 5 files each 5MB in a testcase at least on file fails with this behavior.
And I can reproduce it.

Regards,
vauvenal5

**Comment by tchoulihan** [comment]
Same issue here, I haven't gotten downloading to work, both when using a torrent with dht, or a tTorrent tracker.

**Comment by mpetazzoni** [comment]
This is probably fixed now thanks to some recently merged changes.
