### ISSUE TITLE
Pull Request #45 Introduces Client/Tracker Issue

### ISSUE THREAD

**Issue by ptgoetz** [mpetazzoni/ttorrent#51]
@sroze

When running two clients (one seeder, one leecher) and the tracker on the same host/network interface, the clients fail to communicate with the tracker, and result in the following log message repeating:

`2013-07-23 12:56:05 c.t.t.c.a.Announce [WARN] Current tier or client isn't available`

Reverting to a build prior to this commit fixes the issue.

**Comment by MobileGo2015** [comment]
17:46:44.184 [bt-announce(..333665)] WARN  c.t.t.client.announce.Announce - Current tier or client isn't available
17:46:45.186 [bt-client(..333665)] INFO  com.turn.ttorrent.client.Client - SHARING 0/311 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
17:46:48.190 [bt-client(..333665)] INFO  com.turn.ttorrent.client.Client - SHARING 0/311 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
17:46:49.190 [bt-announce(..333665)] WARN  c.t.t.client.announce.Announce - Current tier or client isn't available
17:46:51.194 [bt-client(..333665)] INFO  com.turn.ttorrent.client.Client - SHARING 0/311 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
17:46:54.197 [bt-announce(..333665)] WARN  c.t.t.client.announce.Announce - Current tier or client isn't available
17:46:54.198 [bt-client(..333665)] INFO  com.turn.ttorrent.client.Client - SHARING 0/311 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
17:46:57.201 [bt-client(..333665)] INFO  com.turn.ttorrent.client.Client - SHARING 0/311 pieces (0.00%) [0/0] with 0/0 peers at 0.00/0.00 kB/s.
 
@ptgoetz @sroze @mpetazzoni , I have tried the code you commit, but it does not work for me. Could you help me for the question?
