### ISSUE TITLE
Error "The requested torrent does not exist on this tracker"

### ISSUE THREAD

**Issue by rain1024** [mpetazzoni/ttorrent#74]
Hi everybody, I just used ttorrent library (https://github.com/mpetazzoni/ttorrent) today.

In tracker server, I start with command 
`TrackerMain.jar -p <port> <directory>`

In client, I start with command
`ClientMain.jar -o <output_directory> -s 3600 test.torrent`

But I got this error message "The requested torrent does not exist on this tracker" in tracker server and client

I think when creating file, client must send an announce message to tracker and then, tracker must create an appropriate torrent file in [directory].

But I can't figure out how to do it.

Please help me and thank all of you so much ^-^

**Comment by jiayunwei** [comment]
Hi,I meet this problem, according to your say, it runs ok!  But  I want to say if I have a new .torrent file, I must restart tracker?

**Comment by mpetazzoni** [comment]
Yes, the tracker here in its default implementation does not automatically refresh the list of torrents it is serving.

**Comment by jiayunwei** [comment]
Thank you very much mpetazzoni. I want to change it, Can I delete this limit(The requested torrent does not exist on this tracker)?
