### ISSUE TITLE
Not Downloading 

### ISSUE THREAD

**Issue by androlizer** [mpetazzoni/ttorrent#85]
private void hello(){
		BasicConfigurator.configure();
		// Get options
		File output = new File(Environment.getExternalStorageDirectory()+"/YIFY Torrents Official/");
    
    
		// Get the .torrent file path
		File torrentPath = new File(
				Environment.getExternalStorageDirectory()+"/YIFY Torrents Official/all.torrent");

		// Start downloading file
		try {        	
			SharedTorrent torrent = SharedTorrent.fromFile(torrentPath, output);
			System.out.println("Starting client for torrent: "
					+ torrent.getName());
			System.out
			.printf("TRACKER COUNT : "+ torrent.getTrackerCount());

			Client client = new Client(InetAddress.getLocalHost(), torrent);

			Tracker tracker = new Tracker(InetAddress.getLocalHost());

			// Then, for each torrent you wish to announce on this tracker, simply created
			// a TrackedTorrent object and pass it to the tracker.announce() method:
			FilenameFilter filter = new FilenameFilter() {
				@Override
				public boolean accept(File dir, String name) {
					return name.endsWith(".torrent");
				}
			};

			for (File f : new File(Environment.getExternalStorageDirectory()+"/YIFY Torrents Official/").listFiles(filter)) {
				tracker.announce(TrackedTorrent.load(f));
			}

			// Once done, you just have to start the tracker's main operation loop:
			tracker.start();
			System.out.println(tracker.getAnnounceUrl().toString());

			try {
				System.out.println("Start to download: " + torrent.getName());
				//client.share(); // SEEDING for completion signal
				//client.download(); // DONE for completion signal
				client.download();

				while (!ClientState.SEEDING.equals(client.getState())) {
					// Check if there's an error
					if (ClientState.ERROR.equals(client.getState())) {
						throw new Exception("ttorrent client Error State");
					}

					// Display statistics                    
					System.out
					.printf("\n%f %% - %d bytes downloaded - %d bytes uploaded\n",
							torrent.getCompletion(),
							torrent.getDownloaded(),
							torrent.getUploaded());

					// Wait one second
					TimeUnit.SECONDS.sleep(1);
				}

				System.out.println("download completed.");
			} catch (Exception e) {
				System.err.println("An error occurs...");
				e.printStackTrace(System.err);
			} finally {
				System.out.println("stop client.");
				client.stop();
			}
		} catch (Exception e) {
			System.err.println("An error occurs...");
			e.printStackTrace(System.err);
		}
	}

Download and upload are not starting stuck at this one please help somebody

**Comment by tchoulihan** [comment]
Same issue here, I can't get downloading to work at all.

**Comment by tchoulihan** [comment]
I've verified that filesize **does** appear to be an issue. Downloading at least started with a small-sized torrent, but wouldn't start with torrents over `1 GB` in size

**Comment by mpetazzoni** [comment]
A change was merged today that should fix a lot of downloading issues. Please re-open if the problem still persists with the code that's in `master` right now.
