### ISSUE TITLE
How to use ttorrent - share multiple torrents on one tcp port

### ISSUE THREAD

**Issue by christf** [mpetazzoni/ttorrent#87]
is this a feature that ttorrent supports out of the box? If so, how can it be used? I looked at the Client class and the ConnectionHandler but it is unclear to me what needs to be done to share multiple torrents on the same port.

**Comment by mpetazzoni** [comment]
ttorrent is designed to work one torrent at a time, using one `Client` instance per shared/downloaded torrent.
