### ISSUE TITLE
download duplicated torrent can not worked

### ISSUE THREAD

**Issue by azimot** [mpetazzoni/ttorrent#89]
i think this is a technical bug 
i create Client Object from a Torrent file and started and then make another Client from same torrent file and started 
first initial Client can downloaded Torrent file , second Client put a lock in this torrent and torrent file can not complete , then if i stopped both Client  and started download again by one Client Object can not worked and i must be deleted torrent files for new Client .

**Comment by mpetazzoni** [comment]
I'm not sure I fully understand your problem, but two `Client` instances can't be downloading onto the same local files. They'd need to be on different directories.
