### ISSUE TITLE
Broken maven dependencies

### ISSUE THREAD

**Issue by zimy** [mpetazzoni/ttorrent#96]
When using in Gradle adding: 

```
repositories {
    mavenCentral()
}
dependencies {
    compile 'com.turn:ttorrent:1.4'
}
```

Executing 

```
$ gradle dependencies
```

gives such output:

```
+--- com.turn:ttorrent:1.4
|    +--- commons-codec:commons-codec:1.8
|    +--- commons-io:commons-io:2.4
|    +--- org.simpleframework:simple:4.1.21
|    +--- org.slf4j:slf4j-log4j12:1.6.4 -> 1.7.7 (*)
|    \--- net.sf:jargs:1.0 FAILED
```

Searching on search.maven.org for jargs was not successful.

**Comment by timabell** [comment]
Just to save anyone else the trouble, the syntax in tthe project build.gradle is:

    allprojects {
        repositories {
            jcenter()
            maven { url 'https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/' } // provides jargs, depended on by ttorrent
        }
    }
